### ISSUE TITLE
Invalid Authorization request

### ISSUE THREAD

**Issue by q-hung** [eralpkaraduman/event_dot_pizza#52]
Redirect URL: https://secure.meetup.com/oauth2/authorize?client_id=96rf1kn6pobffcejakptjgarrf&response_type=token&redirect_uri=https://event.pizza://handle_authorization_redirect/meetup
![Screen Shot 2019-12-26 at 8 34 23](https://user-images.githubusercontent.com/199614/71461992-895a0580-27ba-11ea-935a-3715df32dfa0.jpg)

Happen on Android.

**Comment by eralpkaraduman** [comment]
Yup, i'm refactoring the whole auth thing atm, will fix soon.

**Comment by eralpkaraduman** [comment]
Fixed
